// Generated by gencpp from file lane_detector/Curve.msg
// DO NOT EDIT!


#ifndef LANE_DETECTOR_MESSAGE_CURVE_H
#define LANE_DETECTOR_MESSAGE_CURVE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lane_detector
{
template <class ContainerAllocator>
struct Curve_
{
  typedef Curve_<ContainerAllocator> Type;

  Curve_()
    : a(0.0)
    , b(0.0)
    , c(0.0)  {
    }
  Curve_(const ContainerAllocator& _alloc)
    : a(0.0)
    , b(0.0)
    , c(0.0)  {
  (void)_alloc;
    }



   typedef float _a_type;
  _a_type a;

   typedef float _b_type;
  _b_type b;

   typedef float _c_type;
  _c_type c;





  typedef boost::shared_ptr< ::lane_detector::Curve_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lane_detector::Curve_<ContainerAllocator> const> ConstPtr;

}; // struct Curve_

typedef ::lane_detector::Curve_<std::allocator<void> > Curve;

typedef boost::shared_ptr< ::lane_detector::Curve > CurvePtr;
typedef boost::shared_ptr< ::lane_detector::Curve const> CurveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lane_detector::Curve_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lane_detector::Curve_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lane_detector

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/lunar/share/sensor_msgs/cmake/../msg'], 'lane_detector': ['/home/alex/catkin_ws/src/LaneNetRos/msg'], 'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/lunar/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lane_detector::Curve_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lane_detector::Curve_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lane_detector::Curve_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lane_detector::Curve_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lane_detector::Curve_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lane_detector::Curve_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lane_detector::Curve_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d20f63a7e99cd5689c2dcf93cf2f8085";
  }

  static const char* value(const ::lane_detector::Curve_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd20f63a7e99cd568ULL;
  static const uint64_t static_value2 = 0x9c2dcf93cf2f8085ULL;
};

template<class ContainerAllocator>
struct DataType< ::lane_detector::Curve_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lane_detector/Curve";
  }

  static const char* value(const ::lane_detector::Curve_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lane_detector::Curve_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 a\n\
float32 b\n\
float32 c\n\
";
  }

  static const char* value(const ::lane_detector::Curve_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lane_detector::Curve_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
      stream.next(m.c);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Curve_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lane_detector::Curve_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lane_detector::Curve_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<float>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<float>::stream(s, indent + "  ", v.b);
    s << indent << "c: ";
    Printer<float>::stream(s, indent + "  ", v.c);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LANE_DETECTOR_MESSAGE_CURVE_H
